todo/models.py
from . import db
from sqlalchemy.sql import func
from flask_login import UserMixin


class User(db.Model, UserMixin):
	id = db.Column(db.Integer, primary_key=True)
	name = db.Column(db.String(100), nullable=False)
	email = db.Column(db.String(120), unique=True, nullable=False)
	password = db.Column(db.String(100), nullable=False)
	todos = db.relationship('Todo')

	
class Todo(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	text = db.Column(db.Text, nullable=False)
	date_posted = db.Column(db.DateTime, default=func.now())
	user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

todo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, EmailField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Email, Length, EqualTo, ValidationError
from .models import User


class LoginForm(FlaskForm):
	email = EmailField('Email', 
			validators=[DataRequired(), Email()])
	password = PasswordField('Password',
			validators=[DataRequired(), Length(min=4)])
	remember = BooleanField('Remember')
	submit = SubmitField('Login')


class RegistrationForm(FlaskForm):
	name = StringField('Name', 
			validators=[DataRequired()])
	email = EmailField('Email', 
			validators=[DataRequired(), Email()])
	password = PasswordField('Password', 
			validators=[DataRequired(), Length(min=4)])
	check_password = PasswordField('Check Password', 
			validators=[DataRequired(), EqualTo('password')])
	submit = SubmitField('Sign Up')
	
	def validate_email(self, email):
		user = User.query.filter_by(email=email.data).first()
		if user:
			raise ValidationError("Account already exists for this email")

todo/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
import os
from flask_login import LoginManager


db =  SQLAlchemy()
DB_NAME = "tododb.db"
login_manager = LoginManager()


def create_app():
	app = Flask(__name__)
	
	from .app_config import Config
	app.config.from_object(Config)
		
	db.__init__(app)
	from .models import User, Todo
	create_db(app)
	
	from .views import views
	app.register_blueprint(views)
	
	login_manager.__init__(app)
	login_manager.login_view = "views.log_in"
	login_manager.login_message_category = 'info'
	@login_manager.user_loader
	def load_user(user_id):
		return User.query.get(int(user_id))
	
	return app

	
def create_db(app):
	if not os.path.exists("todo/" + DB_NAME):
		db.create_all(app=app)

todo/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, escape
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from .forms import LoginForm, RegistrationForm
from .models import User, Todo 


views = Blueprint('views', __name__)

@views.route("/", methods= ["GET", "POST"])
def log_in():
	if current_user.is_authenticated:
		return redirect(url_for('views.todo_list'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and check_password_hash(user.password, form.password.data):
			flash('Logged in successfully!', category='success')
			login_user(user, remember=form.remember.data)
			return redirect(url_for('views.todo_list'))
	return render_template("login.html", form=form)

@views.route("/signup", methods= ["GET", "POST"])
def sign_up():
	form = RegistrationForm()
	if form.validate_on_submit():
		new_user = User(name=form.name.data, email=form.email.data, 
					password=generate_password_hash(form.password.data))
		db.session.add(new_user)
		db.session.commit()
		flash("Account created!", category='success')
		return redirect(url_for('views.log_in'))
	return render_template("signup.html", form=form)

@views.route("/todo-list", methods=['GET', 'POST'])
@login_required
def todo_list():
	if request.method == "POST":
		new_task = escape(request.form.get('task'))
		if len(new_task.strip())> 0:
			todo = Todo(text=new_task, user_id=current_user.id)
			db.session.add(todo)
			db.session.commit()
			return redirect(url_for('views.todo_list'))
	return render_template("todolist.html")

@views.route("/log-out")
@login_required
def log_out():
	logout_user()
	return redirect(url_for("views.log_in"))

@views.route("/delete-task/<int:todo_id>")
@login_required
def delete_task(todo_id):
	task = Todo.query.get(todo_id)
	if task:
		db.session.delete(task)
		db.session.commit()
	return redirect(url_for('views.todo_list'))
		
@views.route("/update-task", methods=['GET','POST'])
@login_required
def update_task():
	if request.method == "POST":
		id = request.form.get('task_id')
		new_task = request.form.get('task')
		task = Todo.query.get(int(id))
		if task:
			task.text = new_task
			db.session.commit()	
	return redirect(url_for('views.todo_list'))

todo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>FlaskTodo</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
    <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a9854ac00d.js" crossorigin="anonymous"></script>
</head>
<body>
	<section class="vh-100 custom_bg_color">
		<div>
			<nav class="navbar navbar-expand-sm navbar-light bg-light">
		    	<div class="container-fluid">
		    		{% if current_user.authenticated %}
		    			<a class="navbar-brand" href="{{ url_for('views.todo_list') }}">FlaskTodo</a>
		    		{% else %}
		    			<a class="navbar-brand" href="{{ url_for('views.log_in') }}">FlaskTodo</a>
		    		{% endif %}
		    		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
		      	  <span class="navbar-toggler-icon"></span>
		    		</button>
		    		<div class="collapse navbar-collapse" id="collapsibleNavbar">
		    			<!-- nav items -->
		      	  	<ul class="navbar-nav">
		      	  		{% if not current_user.is_authenticated %}
		        			<li class="nav-item">
		          		  <a class="nav-link" href="{{ url_for('views.log_in') }}">log in</a>
		        			</li>
		        			<li class="nav-item">
		          		  <a class="nav-link" href="{{ url_for('views.sign_up') }}">sign up</a>
		        			</li>
		        			{% else %}
		        			<li class="nav-item">
		          		  <a class="nav-link" href="{{ url_for('views.todo_list') }}">todo list</a>
		        			</li>
		         		   <li class="nav-item">
		          		  <a class="nav-link" href="{{ url_for('views.log_out') }}">log out</a>
		        			</li> 
		        			{% endif %} 
		      	 	 </ul>
		    		</div>
		  	  </div>
		    </nav>
		<div>		
    		<div class="container py-5 px-4 h-100">
        		<div class="row d-flex justify-content-center h-100">
        			{% with messages = get_flashed_messages(with_categories=true) %}
        				{% if messages %}
        					{% for category, message in messages %}
        						<div class="alert alert-{{ category }}">
        							{{ message }}
        						</div>
        					{% endfor %}
        				{% endif %}
        			{% endwith %}
					{% block content %}{% endblock %}
				</div>
			</div>
		</div>
	</section>
	<footer class="custom_bg_color text-center p-3">
	<p>Author: Vaisakh</p>
	</footer>
<script src="{{ url_for('static', filename='index.js') }}" type="text/javascript"></script>
</body>
</html>

todo/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="card">
	<div class="card-body p-4 ">  
		<h3 class="mb-5 text-center">Sign in</h3>
        <form action="{{ url_for('views.log_in') }}" method="POST">
	        {{ form.csrf_token }}
	        
	        {{ form.email.label(class='form-label', for='em') }}
	        {% if form.email.errors %}
	        	{{ form.email(class='form-control form-control-lg is-invalid', id='em') }}
	        	{% for error in form.email.errors %}
	        		<div class="invalid-feedback mb-4">
	        			{{ error }}
	        		</div>
	        	{% endfor %}
	        {% else %}
	        {{ form.email(class='form-control form-control-lg mb-4', id='em') }}
	        {% endif %}
	        
	        {{ form.password.label(class='form-label', for='ps') }}   
	        {% if form.password.errors %}
	        	{{ form.password(class='form-control form-control-lg is-invalid', id='ps') }}
	        	{% for error in form.password.errors %}
	        		<div class="invalid-feedback mb-4">
	        			{{ error }}
	        		</div>
	        	{% endfor %}
	        {% else %}
	        {{ form.password(class='form-control form-control-lg mb-4', id='ps') }}
	        {% endif %}
	        
	        {{ form.remember(class="form-check-input", id="rm") }}
	        {{ form.remember.label(class="form-check-label mb-5", for="rm") }}
	  	  <div class="d-grid ">
				{{ form.submit(class="btn custom_bg_color btn-lg btn-block") }}
	        </div>
    	</form>            
	</div>
</div>
{% endblock %}

todo/templates/signup.html
{% extends "base.html" %}
{% block content %}
<div class="card">
	<div class="card-body p-4 "> 
		<h3 class="mb-5 text-center">Sign up</h3> 
		<form action="{{ url_for('views.sign_up') }}" method="POST">
			{{ form.hidden_tag() }}
			
            {{ form.name.label(class="form-label",for="un") }}                
            {% if form.name.errors %}
            	{{ form.name(id="un", class="form-control form-control-lg is-invalid") }}
            	{% for error in form.name.errors %}
            		<span class="invalid-feedback mb-4">{{ error }}</span>
            	{% endfor %}
            {% else %}
                {{ form.name(id="un", class="form-control form-control-lg mb-4") }}
            {% endif %}
                
            {{ form.email.label(class="form-label", for="em") }}
            {% if form.email.errors %}
            	{{ form.email(id="em", class="form-control form-control-lg is-invalid") }}
            	{% for error in form.email.errors %}
            		<span class="invalid-feedback mb-4">{{ error }}</span>
            	{% endfor %}
            {% else %}
                {{ form.email(id="em", class="form-control form-control-lg mb-4") }}
            {% endif %}
            
            {{ form.password.label(class="form-label", for="pw") }}                
            {% if form.password.errors %}
            	{{ form.password(id="pw", class="form-control form-control-lg is-invalid") }} 
            	{% for error in form.password.errors %}
            		<span class="invalid-feedback mb-4">{{ error }}</span>
                {% endfor %}
			{% else %}
                {{ form.password(id="pw", class="form-control form-control-lg mb-4") }}  
            {% endif %}
                  
            {{ form.check_password.label(class="form-label", for="cpw") }} 
            {% if form.check_password.errors %}
                {{ form.check_password(id="cpw", class="form-control form-control-lg is-invalid ") }} 
                {% for error in form.check_password.errors %}
                	<span class="invalid-feedback mb-4">{{ error }}</span>
                {% endfor %}
            {% else %}
                {{ form.check_password(id="cpw", class="form-control form-control-lg mb-4") }}  
            {% endif %}
            
  		  <div class="d-grid ">
  		  	{{ form.submit(class="btn custom_bg_color btn-lg btn-block") }}
			</div>
		</form>              
	</div>
</div>
{% endblock %}

todo/templates/todolist.html
{% extends "base.html" %}
{% block content %}
	<div class="card"> 
       <div class="card-body p-4 "> 
        <h3 class="mb-5 text-center">Todo List</h3> 
        <form action="{{ url_for('views.todo_list') }}" method="POST" class="d-flex justify-content-center align-items-center mb-4"> 
        	<textarea name="task" class="form-control" placeholder="What do you need to do today?"></textarea> 
        	<button type="submit" class="btn custom_bg_color btn-lg ms-2">Add</button> 
        </form> 
        	<ul class="list-group"> 
 		   {% for task in current_user.todos %}
            	<li class="list-group-item list-group-item-action d-flex align-items-center border-0 mb-2 rounded" style="background-color: #f4f6f7;"> 
          	  <div class="w-100"> 
                	<div class="d-flex">
            			<small class="mb-1">{{ task.date_posted }}</small>
             		   <div class="ms-auto">
             		   {% set collapse_id = "collapse"~task.id %}
             		   {% set href = "#"~ collapse_id %}
                	    <a onclick="edit_task({{ task.id }})" class="custom-color me-2" data-bs-toggle="collapse" href="{{ href }}"> 
            				<i class="fas fa-pencil-alt"></i> 
            			</a>
             		   <a class="custom-color" href="{{ url_for('views.delete_task', todo_id= task.id) }}">
                			<i class="fas fa-trash-alt"></i> 
                		</a> 
                	</div>
          	  </div>
          	  	<form action="{{ url_for('views.update_task') }}" method="POST">
          	  		<input name="task_id" type="hidden" value="{{ task.id }}">
	           	 	<input name="task" type="text" id="{{ task.id }}" class="custom-text-field form-control-plaintext mb-2" value="{{ task.text }}" disabled>
	           	 	<div class="collapse" id="{{ collapse_id }}">
	           	 		<button type="submit" class="btn btn-primary btn-sm">Done</button>
	           	 	</div>
           	 	</form>
          	  </li> 
            {% endfor %}
        	</ul> 
       </div> 
   </div> 
{% endblock %}